
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-servise
  labels:
    env: prod
    owner: IlonaMohilnikova
spec:
  selector:
    project: new #selecting PODs with those labels
  ports:
    - name: app-listener
      protocol: TCP
      port: 80 #LoadBalancer
      targetPort: 80 #POD
  type: ClusterIP
